//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotograf
    {
        public int Id { get; set; }
        public int PersonelId { get; set; }
        public string Fotograf1 { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
