//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Fotograf = new HashSet<Fotograf>();
        }

        public int Id { get; set; }
        [Display(Name = "Departman Seçiniz")]
        public int DepartmanId { get; set; }
        [Display(Name = "Yönetici Seçiniz")]
        public Nullable<int> YoneticiId { get; set; }
        [Required(ErrorMessage = "Personel Adý Zorunludur...")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Personel Soyadý Zorunludur...")]
        public string Soyad { get; set; }
        [Required(ErrorMessage = "Personel Telefon Numarasý Zorunludur....")]
        public string Telefon { get; set; }
        public bool YoneticiMi { get; set; }

        [Display(Name = "Resim Seçiniz")]
        [NotMapped]
        public string ResimYolu { get; set; }

        [NotMapped]
        public HttpPostedFileBase ResimDosyasý { get; set; }

        public virtual Departman Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotograf> Fotograf { get; set; }
    }
}
